//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unipay_Chats.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class unipay_chat_db
    {
        public int unipay_id { get; set; }
        [DisplayName("Login")]
        [Required(ErrorMessage = "Login obligatoire")]
        public string unipay_user { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Mot de passe obligatoire")]
        public string password { get; set; }
        public string email_user { get; set; }
        public Nullable<int> telephone { get; set; }
        public string nom_complet { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}